main: me.GravityIO.TexturePicker.Main
name: TexturePicker
author: GravityIO
version: 0.1
api-version: 1.13

commands:
  texturepicker:
    description: The main interface for TexturePicker features.
    aliases: [tp]
    permission: texturepicker.main

permissions:
  texturepicker.*:
    description: Access to all texturepicker commands
    default: op
    children:
      texturepicker.main: true
      texturepicker.createmap: true
      texturepicker.getmap: true
      texturepicker.removemap: true
  teturepicker.main:
    description: Access to the /texturepicker command
  texturepicker.createmap:
    description: Access to creating maps
  texturepicker.getmap:
    description: Access to getting map images
  texturepicker.removemap:
    deccription: Access to unload / remove loaded maps